# Generated by Django 3.1 on 2022-01-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
